apiVersion: v1
kind: Namespace
metadata:
  name: cwm-keda-external-scaler-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwm-keda-external-scaler
  namespace: cwm-keda-external-scaler-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cwm-keda-external-scaler
  template:
    metadata:
      labels:
        app: cwm-keda-external-scaler
    spec:
      containers:
      - name: cwm-keda-external-scaler
        image: cwm-keda-external-scaler:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CWM_REDIS_HOST
            value: "localhost"
          - name: CWM_REDIS_PORT
            value: "6379"
        ports:
        - containerPort: 50051
      - name: redis
        image: redis:6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cwm-keda-external-scaler
  namespace: cwm-keda-external-scaler-ns
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: cwm-keda-external-scaler
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cwm-keda-external-scaler-ns
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: cwm-keda-external-scaler-ns
spec:
  replicas: 0
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: http
        image: nginx:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-app
  namespace: cwm-keda-external-scaler-ns
spec:
  scaleTargetRef:
    name: test-app
  pollingInterval: 10
  cooldownPeriod:  20
  minReplicaCount: 0
  maxReplicaCount: 10
  # advanced:
  #   restoreToOriginalReplicaCount: true
  #   horizontalPodAutoscalerConfig:
  #     behavior:
  #       scaleDown:
  #         stabilizationWindowSeconds: 30
  #         policies:
  #         - type: Percent
  #           value: 80
  #           periodSeconds: 15
  triggers:
    - type: external
      metadata:
        scalerAddress: cwm-keda-external-scaler.cwm-keda-external-scaler-ns:50051
        isActiveTtlSeconds: "20"
        scalePeriodSeconds: "20"
        scaleMetricName: "bytes_out"
        targetValue: "10"
