name: ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build-and-test:
    name: Build and test external scaler
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: '1.20/stable'
        addons: '["dns", "rbac", "registry", "keda"]'

    - name: Build and deploy external scaler
      env:
        MICROK8S_DOCKER_REGISTRY_ADDR: localhost:32000
        REPO_NAME: cwm-keda-external-scaler
        NAMESPACE: cwm-keda-external-scaler-ns
        TZ: "UTC"
        FMT_DATETIME: "%Y-%m-%dT%H:%M:%S.%8NZ"
        METRIC_KEY: "deploymentid:minio-metrics:bytes_out"
        LAST_ACTION_KEY: "deploymentid:last_action"
        PREFIX_TEST_APP: "test-app"
      run: |
        IMAGE_NAME=$REPO_NAME:latest
        MICROK8S_IMAGE_NAME=$MICROK8S_DOCKER_REGISTRY_ADDR/$IMAGE_NAME
        sed -i "s#$IMAGE_NAME#$MICROK8S_IMAGE_NAME#" deploy.yaml
        echo "Building docker image [$MICROK8S_IMAGE_NAME]"
        docker build -t $MICROK8S_IMAGE_NAME .
        docker push $MICROK8S_IMAGE_NAME
        echo "Deploying test deployment with ScaledObject"
        kubectl apply -f ./deploy.yaml
        echo "Listing all in namespace [$NAMESPACE]"
        kubectl get all -n $NAMESPACE
        echo "Waiting for pod/$POD_NAME_SCALER to be ready"
        POD_NAME_SCALER=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n $NAMESPACE)
        kubectl describe pod/$POD_NAME_SCALER -n $NAMESPACE
        kubectl wait --for=condition=ready --timeout=600s pod/$POD_NAME_SCALER -n $NAMESPACE
        echo "SUCCESS: pod [$POD_NAME_SCALER] is ready"
        echo "Testing 0-to-1 scaling"
        kubectl exec -n $NAMESPACE $POD_NAME_SCALER -c redis -- redis-cli set "$METRIC_KEY" "10"
        kubectl exec -n $NAMESPACE $POD_NAME_SCALER -c redis -- redis-cli set "$LAST_ACTION_KEY" "$(date +"$FMT_DATETIME")"
        echo "Listing all in namespace [$NAMESPACE]"
        kubectl get all -n $NAMESPACE
        POD_NAME_TEST_APP=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n $NAMESPACE | grep "$PREFIX_TEST_APP")
        echo "Waiting for pod/$POD_NAME_TEST_APP to be ready"
        kubectl wait --for=condition=ready --timeout=600s pod/$POD_NAME_TEST_APP -n $NAMESPACE
        echo "SUCCESS: pod/$POD_NAME_TEST_APP is ready"
        echo "SUCCESS: 0-to-1 scaling completed"
