name: ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build-and-test:
    name: Build and test external scaler
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: '1.20/stable'
        addons: '["dns", "rbac", "registry", "keda"]'

    - name: Build and deploy external scaler
      env:
        MICROK8S_DOCKER_REGISTRY_ADDR: localhost:32000
        REPO_NAME: cwm-keda-external-scaler
      run: |
        IMAGE_NAME=$REPO_NAME:latest
        MICROK8S_IMAGE_NAME=$MICROK8S_DOCKER_REGISTRY_ADDR/$IMAGE_NAME
        sed -i "s#$IMAGE_NAME#$MICROK8S_IMAGE_NAME#" ./test/deploy.yaml
        echo "Building docker image [$MICROK8S_IMAGE_NAME]"
        docker build -t $MICROK8S_IMAGE_NAME .
        docker push $MICROK8S_IMAGE_NAME
        ./test/run_scaling_tests.sh
