name: ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build-and-test:
    name: KEDA External Scaler
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: '1.20/stable'
        addons: '["dns", "rbac", "registry", "keda"]'

    - name: Build and deploy external scaler
      env:
        MICROK8S_DOCKER_REGISTRY_ADDR: localhost:32000
        REPO_NAME: cwm-keda-external-scaler
        NAMESPACE: cwm-keda-external-scaler-ns
      run: |
        kubectl cluster-info
        IMAGE_NAME=$REPO_NAME:latest
        MICROK8S_IMAGE_NAME=$MICROK8S_DOCKER_REGISTRY_ADDR/$IMAGE_NAME
        sed -i "s#$IMAGE_NAME#$MICROK8S_IMAGE_NAME#" deploy.yaml
        echo "Building docker image [$MICROK8S_IMAGE_NAME]"
        docker build -t $MICROK8S_IMAGE_NAME .
        docker push $MICROK8S_IMAGE_NAME
        docker images
        echo "Deploying test deployment with ScaledObject"
        kubectl apply -f ./deploy.yaml
        echo "Listing all"
        kubectl get all --all-namespaces
        echo "Waiting for pod to be ready"
        POD_NAME=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n $NAMESPACE)
        kubectl describe pod/$POD_NAME -n $NAMESPACE
        kubectl wait --for=condition=ready --timeout=1800s pod/$POD_NAME -n $NAMESPACE
        echo "pod [$POD_NAME] is ready"
