name: ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  test-and-push-image:
    name: Build and test external scaler
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        sudo ./test/setup.sh
        ./test/run_scaling_tests.sh
        ./test/teardown.sh

    - name: Push docker image to GitHub Packages
      if: github.ref == 'refs/heads/main'
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        ./bin/push_docker_image.sh
