name: ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build-and-test:
    name: KEDA External Scaler
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: '1.20/stable'
        addons: '["dns", "rbac", "storage"]'

    - name: Enable microk8s Helm and KEDA addons
      run: |
        sudo microk8s.enable helm3
        sudo microk8s.enable keda

    - name: Build and deploy external scaler
      env:
        REPO_NAME: cwm-keda-external-scaler
        K8s_NAMESPACE: cwm-keda-external-scaler-ns
      run: |
        docker build -t $REPO_NAME .
        kubectl apply -f ./deploy.yaml
        kubectl --all-namespaces get all
        POD_NAME=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n $K8s_NAMESPACE)
        echo "pod: $POD_NAME"
        kubectl -n $K8s_NAMESPACE describe pod/$POD_NAME
        kubectl -n $K8s_NAMESPACE wait --for=condition=ready --timeout=1800s pod/$POD_NAME
